uplift probabilities refactoring
rubikloud/scikit-learn pull request #2
Opened 2016-11-01 21:06 UTC by RobertChin84

This PR changes the probabilities to normalize within group rather than over the both groups.

`P(active|control) = N(active and control)/N(control) `

as opposed to 

`P(active|control) = N(active and control)/N(control + treated)`

Modified the following:
*  tree.py with a `predict_uplift` method
* forest.py with a `predict_uplift` method

You can reference this sklearn branch with 

`scikit-learn==0.17.1-RUBIKLOUD-2`

2016-11-02 21:34 UTC, apetresc commented
Hey @RobertChin84, I've rebased your branch to hopefully contain the right set of commits. The diffs should now reflect your changes - let me know if they're the right ones :)

2016-11-03 16:47 UTC, RobertChin84 commented
Hi @apetresc  I have had a look at the `uplift_probability_corrections` branch and everything looks fine :)! Do you want to go ahead and do a merge?

2016-11-03 18:28 UTC, bjlkeng requested changes
Math looks correct, just some minor changes below.  Please make sure all the scikit tests pass (including the unit test I added for uplift).

2016-11-03 18:28 UTC, bjlkeng commented on sklearn/ensemble/forest.py
> +        # Parallel loop
Can you fix these comments?  No new line between comments and the block below.

Same with "# Reduce" below.

2016-11-03 18:28 UTC, bjlkeng commented on sklearn/tree/tree.py
> +        if self.n_outputs_ == 1:
You should put an assert here to check that n_outputs == 4 I think.  It should always be 4 in the uplift scenario.

2016-11-03 18:28 UTC, bjlkeng commented on sklearn/ensemble/forest.py
> +        if self.n_outputs_ == 1:
Same comment about n_outputs_ == 4

2016-11-03 18:40 UTC, RobertChin84 commented on sklearn/tree/tree.py
> +        if self.n_outputs_ == 1:
as per our discussion - I will place an asset for the number of classes.

2016-11-07 17:08 UTC, RobertChin84 commented
Updated as per your suggestions @bjlkeng.

2016-11-11 18:38 UTC, bjlkeng approved these changes

2016-11-11 18:39 UTC, merged